account/urls.py
from django.contrib.auth.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.my_profile, name='profile'),
    path('account/', views.account_view, name='account')
]

edit/urls.py
from django.urls import path, include
from . import views

app_name = 'edit'
urlpatterns = [
    path('profile/', views.profile, name='profile')
]

estore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store_information.urls')),
    path('accounts/', include('account.urls')),
    path('search/', include('search.urls')),
    path('sort/', include('sorting.urls')),
    path('edit/', include('edit.urls')),
    path('sort_estore/', include('sorting_estore.urls')),
    path('estore_estore_sort/', include('estore_estore_sort.urls')),
    path('payments/', include('payment.urls'))
]

sorting/urls.py
from django.urls import path, include
from . import views

app_name = 'sort'
urlpatterns = [
    path('clothing/', views.clothing, name='clothing'),
    path('electronics/', views.electronics, name='electronics'),
    path('homeware/', views.homeware, name='homeware'),
    path('other/', views.other, name='other'),
    path('clothing_estore/', views.clothing_estore, name='clothing_estore'),
    path('electronics_estore/', views.electronics_estore, name='electronics_estore'),
    path('homeware_estore/', views.homeware_estore, name='homeware_estore'),
    path('other_estore/', views.other_estore, name='other_estore'),
    path('cosmetics_estore/', views.cosmetics_estore, name='cosmetics_estore'),
    path('vehicles_estore/', views.vehicles_estore, name='vehicles_estore'),
    path('men_collection/', views.men_collection, name='men_collection'),
    path('ladies_collection/', views.ladies_collection, name='ladies_collection'),
    path('kids_collection/', views.kids_collection, name='kids_collection'),
    path('phones_tablets/', views.phones_tablets, name='phones_tablets'),
    path('laptops/', views.laptops, name='laptops'),
    path('appliances_machinery/', views.appliances_machinery, name='appliances_machinery'),
    path('accessories/', views.accessories, name='accessories'),
    path('dining_lounge/', views.dining_lounge, name='dining_lounge'),
    path('kitchen/', views.kitchen, name='kitchen'),
    path('bedroom/', views.bedroom, name='bedroom'),
    path('bathroom/', views.bathroom, name='bathroom'),
    path('skin_care/', views.skin_care, name='skin_care'),
    path('hair_products/', views.hair_products, name='hair_products'),
    path('fragrances/', views.fragrances, name='fragrances'),
    path('cars/', views.cars, name='cars'),
    path('trucks/', views.trucks, name='trucks'),
    path('vehicle_parts/', views.vehicle_parts, name='vehicle_parts'),
    path('event_services/', views.event_services, name='event_services'),
    path('food_services/', views.food_services, name='food_services'),
    path('other_services/', views.other_services, name='other_services'),
    path('other_electronics/', views.other_electronics, name='other_electronics'),
    path('other_beauty_cosmetics/', views.other_beauty_cosmetics, name='other_beauty_cosmetics'),
    path('other_vehicles/', views.other_vehicles, name='other_vehicles'),
    path('other_homeware/', views.other_homeware, name='other_homeware'),


]

sorting_estore/urls.py
from django.urls import path, include
from . import views

app_name = 'sort_estore'
urlpatterns = [
    path('men_collection/', views.men_collection, name='men_collection'),
    path('ladies_collection/', views.ladies_collection, name='ladies_collection'),
    path('kids_collection/', views.kids_collection, name='kids_collection'),
    path('phones_tablets/', views.phones_tablets, name='phones_tablets'),
    path('laptops/', views.laptops, name='laptops'),
    path('appliances_machinery/', views.appliances_machinery, name='appliances_machinery'),
    path('accessories/', views.accessories, name='accessories'),
    path('dining_lounge/', views.dining_lounge, name='dining_lounge'),
    path('kitchen/', views.kitchen, name='kitchen'),
    path('bedroom/', views.bedroom, name='bedroom'),
    path('bathroom/', views.bathroom, name='bathroom'),
    path('skin_care/', views.skin_care, name='skin_care'),
    path('hair_products/', views.hair_products, name='hair_products'),
    path('fragrances/', views.fragrances, name='fragrances'),
    path('cars/', views.cars, name='cars'),
    path('trucks/', views.trucks, name='trucks'),
    path('vehicle_parts/', views.vehicle_parts, name='vehicle_parts'),
    path('event_services/', views.event_services, name='event_services'),
    path('food_services/', views.food_services, name='food_services'),
    path('other_services/', views.other_services, name='other_services'),
    path('other/', views.other, name='other'),
    path('men_collection_hotdeals/', views.men_collection_hotdeals, name='men_collection_hotdeals'),
    path('ladies_collection_hotdeals/', views.ladies_collection_hotdeals, name='ladies_collection_hotdeals'),
    path('kids_collection_hotdeals/', views.kids_collection_hotdeals, name='kids_collection_hotdeals'),
    path('phones_tablets_hotdeals/', views.phones_tablets_hotdeals, name='phones_tablets_hotdeals'),
    path('laptops_hotdeals/', views.laptops_hotdeals, name='laptops_hotdeals'),
    path('appliances_machinery_hotdeals/', views.appliances_machinery_hotdeals, name='appliances_machinery_hotdeals'),
    path('accessories_hotdeals/', views.accessories_hotdeals, name='accessories_hotdeals'),
    path('dining_lounge_hotdeals/', views.dining_lounge_hotdeals, name='dining_lounge_hotdeals'),
    path('kitchen_hotdeals/', views.kitchen_hotdeals, name='kitchen_hotdeals'),
    path('bedroom_hotdeals/', views.bedroom_hotdeals, name='bedroom_hotdeals'),
    path('bathroom_hotdeals/', views.bathroom_hotdeals, name='bathroom_hotdeals'),
    path('skin_care_hotdeals/', views.skin_care_hotdeals, name='skin_care_hotdeals'),
    path('hair_products_hotdeals/', views.hair_products_hotdeals, name='hair_products_hotdeals'),
    path('fragrances_hotdeals/', views.fragrances_hotdeals, name='fragrances_hotdeals'),
    path('cars_hotdeals/', views.cars_hotdeals, name='cars_hotdeals'),
    path('trucks_hotdeals/', views.trucks_hotdeals, name='trucks_hotdeals'),
    path('vehicle_parts_hotdeals/', views.vehicle_parts_hotdeals, name='vehicle_parts_hotdeals'),
    path('event_services_hotdeals/', views.event_services_hotdeals, name='event_services_hotdeals'),
    path('food_services_hotdeals/', views.food_services_hotdeals, name='food_services_hotdeals'),
    path('other_services_hotdeals/', views.other_services_hotdeals, name='other_services_hotdeals'),
    path('other_hotdeals/', views.other_hotdeals, name='other_hotdeals'),
    path('other_electronics/', views.other_electronics, name='other_electronics'),
    path('other_beauty_cosmetics/', views.other_beauty_cosmetics, name='other_beauty_cosmetics'),
    path('other_vehicles/', views.other_vehicles, name='other_vehicles'),
    path('other_homeware/', views.other_homeware, name='other_homeware'),
    path('other_electronics_hotdeals/', views.other_electronics_hotdeals, name='other_electronics_hotdeals'),
    path('other_beauty_cosmetics_hotdeals/', views.other_beauty_cosmetics_hotdeals, name='other_beauty_cosmetics_hotdeals'),
    path('other_vehicles_hotdeals/', views.other_vehicles_hotdeals, name='other_vehicles_hotdeals'),
    path('other_homeware_hotdeals/', views.other_homeware_hotdeals, name='other_homeware_hotdeals'),

]

store_information/urls.py
from django.contrib.auth.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'store_information'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery/', views.items, name='gallery'),
    path('sell_product/', views.upload_item, name='sell_product'),
    path('create_estore/', views.create_estore, name='create_estore'),
    path('item_estore/', views.item_estore, name='item_estore'),
    path('welcome/', views.welcome, name='welcome'),
    path('about_estore/', views.about_estore, name='about_estore'),
    path('about_us/', views.about_us, name='about_us'),
    path('gallery/<int:gallerie_id>/', views.gallerie, name='gallerie'),
    path('estores/', views.estores, name='estores'),
    path('hotdeals/', views.hotdeals, name='hotdeals'),
    path('upload_hot_deals/', views.upload_hot_deals, name='upload_hot_deals'),
    path('hotdeals/<int:hotdeal_id>/', views.hotdeal, name='hotdeal'),
    path('estores_estore/<int:estore_id>/', views.estores_estore, name='estores_estore'),
    path('product_estore/<int:product_estore_id>/', views.product_estore, name='product_estore'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('my_listings/', views.my_listings, name='my_listings'),
    path('my_gallery/', views.my_gallery, name='my_gallery'),
    path('estore_coupon/', views.estore_coupon, name='estore_coupon'),
    path('create/', views.create, name='create'),
    path('no_store', views.no_store, name='no_store'),
    path('edit_store/<int:estore_id>/', views.edit_store, name='edit_store'),
    path('terms_conditions/', views.terms_conditions, name='terms_conditions')

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

store_information/views.py
from django.shortcuts import render, redirect
from .models import Item, ItemEstore, HotDeals, WishList
from .forms import ItemForm, Create_EStoreForm, ItemEstoreForm, EStore, HotDealsForm
from account.models import Account
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
# Create your views here.


@login_required()
def index(request):
    items2 = Item.objects.filter(location='Harare').order_by('-date_added')
    hotdeals = HotDeals.objects.order_by('-date_added')
    context = {'items2': items2, 'hot_deals': hotdeals}
    return render(request, 'store_information/index.html', context)


def items(request):
    items = Item.objects.order_by('-date_added')
    context = {'items': items}
    return render(request, 'store_information/gallery.html', context)


@login_required()
def upload_item(request):
    if request.method != 'POST':
        form = ItemForm()
    else:
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.owner = request.user
            new_item.save()
            data = form.cleaned_data.get("price")
            if data >= '0':
                return redirect('store_information:hotdeals')
    context = {'form': form}
    return render(request, 'store_information/sell_product.html', context)

@login_required()
def create_estore(request):
    if request.method != 'POST':
        form = Create_EStoreForm()
    else:
        form = Create_EStoreForm(request.POST, request.FILES)
        if form.is_valid():
            new_estore = form.save(commit=False)
            new_estore.owner = request.user
            new_estore.save()
            return redirect('store_information:about_estore')
    context = {'form': form}
    return render(request, 'store_information/create_estore.html', context)



@login_required()
def item_estore(request):
    if request.method != 'POST':
        form = ItemEstoreForm()
    else:
        form = ItemEstoreForm(request.POST, request.FILES)
        if form.is_valid():

            new_itemestore = form.save(commit=False)
            new_itemestore.owner = request.user
            new_itemestore.save()
            return redirect('store_information:about_estore')
    context = {'form': form}
    return render(request, 'store_information/item_estore.html', context)


def welcome(request):
    return render(request, 'store_information/welcome.html')


@login_required()
def about_estore(request):
    abouts = EStore.objects.filter(owner=request.user)
    context = {'abouts': abouts}
    return render(request, 'store_information/about_estore.html', context)


def about_us(request):
    return render(request, 'store_information/about_us.html')


@login_required()
def gallerie(request, gallerie_id):
    wishes = []
    gallerie = Item.objects.get(id=gallerie_id)
    estores = gallerie.owner.estore_set.order_by('-date_added')
    items2 = Item.objects.filter(location=request.user.location)
    user = request.user
    wishlist = user.my_wishlist.all()
    for wish in wishlist:
        wishes.append(wish.product)
    context = {'gallerie': gallerie, 'items2': items2, 'user': user, 'wishes': wishes, 'estores': estores}
    return render(request, 'store_information/gallerie.html', context)


@login_required()
def estores(request):
    estores = EStore.objects.order_by('-date_added')
    context = {'estores': estores}
    return render(request, 'store_information/estores.html', context)


@login_required()
def hotdeals(request):
    hotdeals = HotDeals.objects.order_by('-date_added')
    context = {'hotdeals': hotdeals}
    return render(request, 'store_information/hotdeals.html', context)


@login_required()
def upload_hot_deals(request):
    if request.method != 'POST':
        form = HotDealsForm()
    else:
        form = HotDealsForm(request.POST, request.FILES)
        if form.is_valid():
            new_hot_deal = form.save(commit=False)
            new_hot_deal.owner = request.user
            new_hot_deal.save()
            return redirect('store_information:hotdeals')
    context = {'form': form}
    return render(request, 'store_information/upload_hot_deals.html', context)


@login_required()
def hotdeal(request, hotdeal_id):
    hotdeal = HotDeals.objects.get(id=hotdeal_id)
    estores = hotdeal.owner.estore_set.order_by('-date_added')
    context = {'hotdeal': hotdeal, 'estores': estores}
    return render(request, 'store_information/hot_deal.html', context)


@login_required()
def estores_estore(request, estore_id):
    estores_estore = EStore.objects.get(id=estore_id)
    items = estores_estore.itemestore_set.order_by('-date_added')
    context = {'estores_estore': estores_estore, 'items': items}
    return render(request, 'store_information/estores_estore.html', context)


@login_required()
def product_estore(request, product_estore_id):
    product_estore = ItemEstore.objects.get(id=product_estore_id)
    estores = product_estore.owner.estore_set.order_by('-date_added')
    context = {'product_estore': product_estore, 'estores': estores}
    return render(request, 'store_information/product_estore.html', context)

@login_required()
def wishlist(request):
    user = request.user
    wishlist = user.my_wishlist.all()
    context = {'wishlist': wishlist}
    print(wishlist)
    for wish in wishlist:
        print(wish.product)
    return render(request, 'store_information/wishlist.html', context)


@login_required()
def add_to_wishlist(request):
    data = json.loads(request.body)
    item_id = data['item_id']
    action = data['action']

    print(item_id, action)

    if item_id and action:
        try:
            item = Item.objects.get(id=item_id)
            if action == 'add':
                WishList.objects.get_or_create(product=item, owner=request.user)
                
            else:
                WishList.objects.filter(product=item, owner=request.user).delete()
            return JsonResponse({'status': 'ok'})

        except Item.DoesNotExist:
            return JsonResponse({'status': 'error'})

    return JsonResponse({'status': 'error'})


@login_required()
def my_listings(request):
    items = Item.objects.filter(owner=request.user)
    context = {'items': items}
    return render(request, 'store_information/my_listings.html', context)


def my_gallery(request):
    return render(request, 'store_information/final draft/myGallery.html')

@login_required()
def estore_coupon(request):
    return render(request, 'store_information/estore_coupon.html')

@login_required()
def create(request):
    return render(request, 'store_information/create.html')


@login_required()
def no_store(request):
    return render(request, 'store_information/no_store.html')


@login_required()
def edit_store(request, estore_id):
    estore = EStore.objects.get(id=estore_id)
    if request.method != 'POST':
        form = Create_EStoreForm(instance=estore)
    else:
        form = Create_EStoreForm(request.POST, request.FILES, instance=estore)
        if form.is_valid():
            form.save()
            return redirect('store_information:about_estore')
    context = {'estore': estore, 'form': form}
    return render(request, 'store_information/edit_store.html', context)


def terms_conditions(request):
    return render(request, 'store_information/terms_conditions.html')

store_information/templates/store_information/create_estore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Estore</title>
</head>
{% extends 'store_information/base.html' %}
{% load static %}
<body>
{% block conntent %}


    <section class="logoRS">
        <img class="logoR" src="{% static 'media/main-logo.png' %}" alt="">
    </section>

    <div class="headline-H">
        <h1>Create an E-store</h1>
        <p>Upload as many products as you want with the help of an estore</p>
    </div>


    <section class="conditions">
        <div class="condition">
            <div class="savage">
                <form method="post" action="{% url 'store_information:create_estore' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                    </table>

                    <br>
                    <p>By clicking "create" you are agreeing to our <a href="{% url 'store_information:terms_conditions' %}">Terms and Conditions</a></p>

                    <button class="btn-login" type="submit">Create</button>
                </form>
                </div>

                <div class="L">

        </div>

        </div>
    </section>

    <footer class="featured foot-det">
        <div class="col">
            <img class="logor" src="{% static 'media/main-logo.png' %}" alt="">
            <h3>Contact</h3>
            <p><strong>WhatsApp :</strong> +263 77 684 2894</p>
            <p><strong>Phone : </strong>  +263 77 635 0319 </p>
            <div class="follow">
                <h3>Follow Us</h3>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="{% url 'store_information:about_us' %}">About Us</a>
            <a href="{% url 'store_information:terms_conditions' %}">Terms & Conditions</a>
            <a href="#">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            <a href="{% url 'account:profile' %}">Sign In</a>
            <a href="{% url 'store_information:wishlist' %}">My Wishlist</a>
            <a href="{% url 'store_information:about_us' %}">Help</a>
        </div>

        <div class="col install">
            <h3>Install Our App</h3>
            <p>Coming soon</p>
            <div class="row app">
                <!-- This is the buttons for downoloading our app-->
                <img src="{% static 'media/undraw_under_construction_-46-pa.svg' %}" alt="">
            </div>
            <p>Secured Payment Gateways</p>
            <div class="row pay">
                <!-- Payment gateways i.e Ecocash -->
               <ul>
                   <li>Ecocash</li>
                   <li>VISA Mastercard</li>
                   <li>Direct Bank Transfer</li>
               </ul>
            </div>
        </div>


        <section class="line">
            <p>Copyright 2022 @SquareMarket. All rights reserved.</p>
        </section>

    </footer>


{% endblock conntent %}
</body>
</html>

store_information/templates/store_information/estores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Estore</title>
</head>
{% extends 'store_information/base.html' %}
{% load static %}
<body>




{% block conntent %}

    <header class="H1">
        <image class="logo" src="{% static '/media/main-logo.png' %}"></image>
        <div class="search-nav-bar">
            <form action="{% url 'store_search_results' %}" method="get">
                <input name="q" type="text" placeholder="Search...">
            </form>
        </div>


        {% if request.user.is_authenticated %}

            <div class="nav-tab">
                <div class="sml-search">
                    <a href="{% url 'estore_mobile' %}"><i class="fas fa-search"></i></a>
                </div>
                <div class="user"onclick="window.location.href='{% url 'account:profile' %}';">
                    <img src="{{ request.user.profile_pic.url }}" alt="">
                </div>
             </div>

            <div class="sml-nav">
                <div class="sml-search">
                    <a href="{% url 'estore_mobile' %}"><i class="fas fa-search"></i></a>
                </div>

                <div class="sml-nav-2">

                    <button class="mobile-toggle"
                        aria-controls="pry-nav" aria-expanded="false">
                        <span class="sr-only">Menu</span>
                    </button>
                     <nav>
                        <ul id="pry-nav" data-visible="false" class="pry-nav">
                            <div class="profile-acc">
                                <img src="{{ request.user.profile_pic.url }}" alt="">
                                <div class="profile-acc-details">
                                    <h2><span><i class="fas fa-user"></i></span>{{ request.user.username }}</h2>
                                    <a href="{% url 'account:profile' %}">My Dashboard</a>
                                </div>
                            </div>
                            <li><a href="{% url 'store_information:index' %}"><span><i class="fas fa-home"></i></span> Home</a></li>
                            <li><a href="{% url 'store_information:gallery' %}"><span><i class="fas fa-image"></i></span> Gallery</a></li>
                            <li><a href="{% url 'store_information:about_us' %}"><span><i class="fas fa-users"></i></span> About Us</a></li>
                            <li><a href="{% url 'store_information:estores' %}"><span><i class="fas fa-store"></i></span> E Stores</a></li>
                            <li><a href="{% url 'store_information:hotdeals' %}"><span> <i class="fas fa-percent"></i></span> Hot Deals</a></li>
                            <li><a href="{% url 'account:logout' %}"><span> <i class="fas fa-sign-out-alt"></i></span> Log Out</a></li>
                         </ul>
                    </nav>
                </div>
            </div>
        {% else %}
            <a href="{% url 'account:login' %}" class="btn">Sign In</a>
        {% endif %}



    </header>

    <header class="H2-container">
        <nav class="nav-bar-bar">
            <ul>
                <li><a href="{% url 'store_information:index' %}">Home</a></li>
                <li><a href="{% url 'store_information:about_us' %}">About Us</a></li>
                <li><a href="{% url 'store_information:gallery' %}">Gallery</a></li>
                <li><a href="{% url 'store_information:estores' %}">E Store</a></li>
                <li><a href="{% url 'store_information:hotdeals' %}">Hot Deals</a></li>
            </ul>
        </nav>
    </header>

        <section class="container">
            <h1>#E-Stores</h1>
            <p>Visit our online stores by our different vendors</p>
            <a href="{% url 'store_information:estore_coupon' %}" class="btn-S">Create E-Store</a>
        </section>



    <section class="cat-menu">
       <nav>
            <label for="btwn" class="btn-D">Categories
            <span class="fas fa-caret-down"></span>
        </label>
        <input class="tick" type = "checkbox" id="btwn">
         <ul class="menu-bar">
             <li>
            <label for="btwn-1" class="first-menu">Clothing
                <span class="fas fa-caret-down"></span>
            </label>
            <input class="tick" type = "checkbox" id="btwn-1">
                        <ul>
                <li><a href="{% url 'sort_estore:men_collection' %}">Men Collection</a></li>
                <li><a href="{% url 'sort_estore:ladies_collection' %}">Ladies Collection</a></li>
                <li><a href="{% url 'sort_estore:kids_collection' %}">Kids Collection</a></li>
                <li><a href="{% url 'sort_estore:accessories' %}">Accessories</a></li>
            </ul>
            </li>
            <li>
                <label for="btwn-2" class="second-menu">Electronics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-2">

                <ul>
                    <li><a href="{% url 'sort_estore:phones_tablets' %}">Phones and Tablets</a></li>
                    <li><a href="{% url 'sort_estore:appliances_machinery' %}">Appliances and Machinery</a></li>
                    <li><a href="{% url 'sort_estore:laptops' %}">Laptops</a></li>
                    <li><a href="{% url 'sort_estore:other_electronics' %}">Other</a></li>

                </ul>
            </li>
            <li>
                <label for="btwn-3" class="third-menu">Homeware
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-3">
                 <ul>
                    <li><a href="{% url 'sort_estore:dining_lounge' %}">Lounge and Dining</a></li>
                    <li><a href="{% url 'sort_estore:kitchen' %}">Kitchen</a></li>
                    <li><a href="{% url 'sort_estore:bedroom' %}">Bedroom</a></li>
                    <li><a href="{% url 'sort_estore:bathroom' %}">Bathroom</a></li>
                     <li><a href="{% url 'sort_estore:other_homeware' %}">Other</a></li>
                </ul>
            </li>
             <li>
                <label for="btwn-4" class="fourth-menu">Beauty and Cosmetics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-4">
                 <ul>
                    <li><a href="{% url 'sort_estore:skin_care' %}">Skin Care</a></li>
                    <li><a href="{% url 'sort_estore:hair_products' %}">Hair products</a></li>
                    <li><a href="{% url 'sort_estore:fragrances' %}">Fragrances</a></li>
                     <li><a href="{% url 'sort_estore:other_beauty_cosmetics' %}">Other</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-5" class="fifth-menu">Vehicles
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-5">
                 <ul>
                    <li><a href="{% url 'sort_estore:cars' %}">Cars</a></li>
                    <li><a href="{% url 'sort_estore:trucks' %}">Trucks</a></li>
                     <li><a href="{% url 'sort_estore:other_vehicles' %}">Other</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-6" class="fifth-menu">Services and Category
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-6">
                 <ul>
                    <li><a href="{% url 'sort_estore:event_services' %}">Event Services</a></li>
                    <li><a href="{% url 'sort_estore:food_services' %}">Food Services</a></li>
                    <li><a href="{% url 'sort_estore:other_services' %}">Other Services</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-7" class="sixth-menu">
                    <a href="{% url 'sort_estore:other' %}" class="sixth-menu">Other</a>
                </label>
            </li>
         </ul>
        </nav>

    </section>



    <section id="stores" class="featured">
        <div class="container-stores">
        {% for estore in estores %}
        <div class="store-card">

                 <div class="store-card-top">

                    <div class="store-details">
                            <h2 class="store">{{ estore.store_name }}</h2>
                        <div class="location">
                            <i class="fas fa-map-marker-alt"></i>
                            <h3>{{ estore.location }}</h3>
                        </div>
                    </div>

                    <div class="store-pro">
                        <img src="{{ estore.profile_pic.url }}" alt="">
                    </div>

                </div>
                <div class="store-card-bottom">
                    <a href="{% url 'store_information:estores_estore' estore.id %}" class="btn-St">Visit Store</a>
                </div>
        </div>
        {% empty %}
            <li>No estores have been created yet.</li>
        {% endfor %}
        </div>


    </section>


    <footer class="featured">
        <div class="col">
            <image class="logo" src="{% static '/media/main-logo.png' %}"></image>
            <h3>Contact</h3>
            <p><strong>WhatsApp :</strong> +263 77 684 2894</p>
            <p><strong>Phone : </strong>  +263 77 635 0319 </p>
            <div class="follow">
                <h3>Follow Us</h3>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="{% url 'store_information:about_us' %}">About Us</a>
            <a href="{% url 'store_information:terms_conditions' %}">Terms & Conditions</a>
            <a href="#">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            <a href="#">Sign In</a>
            <a href="#">My Wishlist</a>
            <a href="{% url 'store_information:about_us' %}">Help</a>
        </div>

        <div class="col install">
            <h3>Install Our App</h3>
            <p>For easier access of our content</p>
            <div class="row">
                <!-- This is the buttons for downoloading our app-->
            </div>
            <p>Secured Payment Gateways</p>
            <div class="row">
                <!-- Payment gateways i.e Ecocash -->
            </div>
        </div>


        <section class="line">
            <p>Copyright 2022 @SquareMarket. All rights reserved.</p>
        </section>

    </footer>
{% endblock conntent %}

</body>
</html>

store_information/templates/store_information/search_mobile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>