account/urls.py
from django.contrib.auth.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.my_profile, name='profile'),
    path('account/', views.account_view, name='account')
]

edit/urls.py
from django.urls import path, include
from . import views

app_name = 'edit'
urlpatterns = [
    path('profile/', views.profile, name='profile')
]

estore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store_information.urls')),
    path('accounts/', include('account.urls')),
    path('search/', include('search.urls')),
    path('sort/', include('sorting.urls')),
    path('edit/', include('edit.urls')),
    path('sort_estore/', include('sorting_estore.urls')),
    path('estore_estore_sort/', include('estore_estore_sort.urls')),
    path('payments/', include('payment.urls'))
]

sorting/urls.py
from django.urls import path, include
from . import views

app_name = 'sort'
urlpatterns = [
    path('clothing/', views.clothing, name='clothing'),
    path('electronics/', views.electronics, name='electronics'),
    path('homeware/', views.homeware, name='homeware'),
    path('other/', views.other, name='other'),
    path('clothing_estore/', views.clothing_estore, name='clothing_estore'),
    path('electronics_estore/', views.electronics_estore, name='electronics_estore'),
    path('homeware_estore/', views.homeware_estore, name='homeware_estore'),
    path('other_estore/', views.other_estore, name='other_estore'),
    path('cosmetics_estore/', views.cosmetics_estore, name='cosmetics_estore'),
    path('vehicles_estore/', views.vehicles_estore, name='vehicles_estore'),
    path('men_collection/', views.men_collection, name='men_collection'),
    path('ladies_collection/', views.ladies_collection, name='ladies_collection'),
    path('kids_collection/', views.kids_collection, name='kids_collection'),
    path('phones_tablets/', views.phones_tablets, name='phones_tablets'),
    path('laptops/', views.laptops, name='laptops'),
    path('appliances_machinery/', views.appliances_machinery, name='appliances_machinery'),
    path('accessories/', views.accessories, name='accessories'),
    path('dining_lounge/', views.dining_lounge, name='dining_lounge'),
    path('kitchen/', views.kitchen, name='kitchen'),
    path('bedroom/', views.bedroom, name='bedroom'),
    path('bathroom/', views.bathroom, name='bathroom'),
    path('skin_care/', views.skin_care, name='skin_care'),
    path('hair_products/', views.hair_products, name='hair_products'),
    path('fragrances/', views.fragrances, name='fragrances'),
    path('cars/', views.cars, name='cars'),
    path('trucks/', views.trucks, name='trucks'),
    path('vehicle_parts/', views.vehicle_parts, name='vehicle_parts'),
    path('event_services/', views.event_services, name='event_services'),
    path('food_services/', views.food_services, name='food_services'),
    path('other_services/', views.other_services, name='other_services'),
    path('other_electronics/', views.other_electronics, name='other_electronics'),
    path('other_beauty_cosmetics/', views.other_beauty_cosmetics, name='other_beauty_cosmetics'),
    path('other_vehicles/', views.other_vehicles, name='other_vehicles'),
    path('other_homeware/', views.other_homeware, name='other_homeware'),


]

store_information/urls.py
from django.contrib.auth.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'store_information'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery/', views.items, name='gallery'),
    path('sell_product/', views.upload_item, name='sell_product'),
    path('create_estore/', views.create_estore, name='create_estore'),
    path('item_estore/', views.item_estore, name='item_estore'),
    path('welcome/', views.welcome, name='welcome'),
    path('about_estore/', views.about_estore, name='about_estore'),
    path('about_us/', views.about_us, name='about_us'),
    path('gallery/<int:gallerie_id>/', views.gallerie, name='gallerie'),
    path('estores/', views.estores, name='estores'),
    path('hotdeals/', views.hotdeals, name='hotdeals'),
    path('upload_hot_deals/', views.upload_hot_deals, name='upload_hot_deals'),
    path('hotdeals/<int:hotdeal_id>/', views.hotdeal, name='hotdeal'),
    path('estores_estore/<int:estore_id>/', views.estores_estore, name='estores_estore'),
    path('product_estore/<int:product_estore_id>/', views.product_estore, name='product_estore'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('my_listings/', views.my_listings, name='my_listings'),
    path('my_gallery/', views.my_gallery, name='my_gallery'),
    path('estore_coupon/', views.estore_coupon, name='estore_coupon'),
    path('create/', views.create, name='create'),
    path('no_store', views.no_store, name='no_store'),
    path('edit_store/<int:estore_id>/', views.edit_store, name='edit_store'),
    path('terms_conditions/', views.terms_conditions, name='terms_conditions')

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

sorting/models.py
from django.db import models

# Create your models here.

sorting/views.py
from django.shortcuts import render
from store_information.models import ItemEstore, Item, EStore, HotDeals
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required()
def clothing(request):
    clothing = Item.objects.filter(category='Clothing')
    clothing_estore = EStore.objects.filter(category='Clothing')
    context = {'clothing': clothing, 'clothing_estore': clothing_estore}
    return render(request, 'sorting/clothing.html', context)


@login_required()
def electronics(request):
    electronics = Item.objects.filter(category='Electronics')
    electronics_estore = EStore.objects.filter(category='Electronics')
    context = {'electronics': electronics, 'electronics_estore': electronics_estore}
    return render(request, 'sorting/electronics.html', context)


@login_required()
def homeware(request):
    homeware = Item.objects.filter(category='Homeware')
    homeware_estore = EStore.objects.filter(category='Homeware')
    context = {'homeware': homeware, 'homeware_estore': homeware_estore}
    return render(request, 'sorting/homeware.html', context)


@login_required()
def other(request):
    other = Item.objects.filter(category='Other')
    other_estore = EStore.objects.filter(category='Other')
    context = {'other': other, 'other_estore': other_estore}
    return render(request, 'sorting/other.html', context)


@login_required()
def clothing_estore(request):
    clothing_estore = EStore.objects.filter(category='Clothing')
    context = {'clothing_estore': clothing_estore}
    return render(request, 'sorting/clothing_estore.html', context)


@login_required()
def electronics_estore(request):
    electronics_estore = EStore.objects.filter(category='Electronics')
    context = {'electronics_estore': electronics_estore}
    return render(request, 'sorting/electronics_estore.html', context)


@login_required()
def homeware_estore(request):
    homeware_estore = EStore.objects.filter(category='Homeware')
    context = {'homeware_estore': homeware_estore}
    return render(request, 'sorting/homeware_estore.html', context)


@login_required()
def other_estore(request):
    other_estore = EStore.objects.filter(category='Other')
    context = {'other_estore': other_estore}
    return render(request, 'sorting/other_estore.html', context)


@login_required()
def cosmetics_estore(request):
    cosmetics_estore = EStore.objects.filter(category='1')
    context = {'cosmetics_estore': cosmetics_estore}
    return render(request, 'sorting/cosmetics_estore.html', context)


@login_required()
def vehicles_estore(request):
    vehicles_estore = EStore.objects.filter(category='Vehicles')
    context = {'vehicles_estore': vehicles_estore}
    return render(request, 'sorting/vehicles_estore.html', context)


@login_required()
def men_collection(request):
    men_collection = Item.objects.filter(category='1')
    context = {'men_collection': men_collection}
    return render(request, 'sorting/men_collection.html', context)


@login_required()
def ladies_collection(request):
    ladies_collection = Item.objects.filter(category='2')
    context = {'ladies_collection': ladies_collection}
    return render(request, 'sorting/ladies_collection.html', context)


@login_required()
def kids_collection(request):
    kids_collection = Item.objects.filter(category='3')
    context = {'kids_collection': kids_collection}
    return render(request, 'sorting/kids_collection.html', context)


@login_required()
def phones_tablets(request):
    phones_tablets = Item.objects.filter(category='4')
    context = {'phones_tablets': phones_tablets}
    return render(request, 'sorting/phones_tablets.html', context)


@login_required()
def laptops(request):
    laptops = Item.objects.filter(category='5')
    context = {'laptops': laptops}
    return render(request, 'sorting/laptops.html', context)


@login_required()
def appliances_machinery(request):
    appliances_machinery = Item.objects.filter(category='6')
    context = {'appliances_machinery': appliances_machinery}
    return render(request, 'sorting/appliances_machinery.html', context)


@login_required()
def accessories(request):
    accessories = Item.objects.filter(category='7')
    context = {'accessories': accessories}
    return render(request, 'sorting/accessories.html', context)


@login_required()
def dining_lounge(request):
    dining_lounge = Item.objects.filter(category='8')
    context = {'dining_lounge': dining_lounge}
    return render(request, 'sorting/dining_lounge.html', context)


@login_required()
def kitchen(request):
    kitchen = Item.objects.filter(category='9')
    context = {'kitchen': kitchen}
    return render(request, 'sorting/kitchen.html', context)


@login_required()
def bedroom(request):
    bedroom = Item.objects.filter(category='10')
    context = {'bedroom': bedroom}
    return render(request, 'sorting/bedroom.html', context)


@login_required()
def bathroom(request):
    bathroom = Item.objects.filter(category='11')
    context = {'bathroom': bathroom}
    return render(request, 'sorting/bathroom.html', context)


@login_required()
def skin_care(request):
    skin_care = Item.objects.filter(category='12')
    context = {'skin_care': skin_care}
    return render(request, 'sorting/skin_care.html', context)


@login_required()
def hair_products(request):
    hair_products = Item.objects.filter(category='13')
    context = {'hair_products': hair_products}
    return render(request, 'sorting/hair_products.html', context)


@login_required()
def fragrances(request):
    fragrances = Item.objects.filter(category='14')
    context = {'fragrances': fragrances}
    return render(request, 'sorting/fragrances.html', context)


@login_required()
def cars(request):
    cars = Item.objects.filter(category='15')
    context = {'cars': cars}
    return render(request, 'sorting/cars.html', context)


@login_required()
def trucks(request):
    trucks = Item.objects.filter(category='16')
    context = {'trucks': trucks}
    return render(request, 'sorting/trucks.html', context)


@login_required()
def vehicle_parts(request):
    vehicle_parts = Item.objects.filter(category='17')
    context = {'vehicle_parts': vehicle_parts}
    return render(request, 'sorting/vehicle_parts.html', context)


@login_required()
def event_services(request):
    event_services = Item.objects.filter(category='18')
    context = {'event_services': event_services}
    return render(request, 'sorting/event_services.html', context)


@login_required()
def food_services(request):
    food_services = Item.objects.filter(category='19')
    context = {'food_services': food_services}
    return render(request, 'sorting/food_services.html', context)


@login_required()
def other_services(request):
    other_services = Item.objects.filter(category='20')
    context = {'other_services': other_services}
    return render(request, 'sorting/other_services.html', context)


@login_required()
def other(request):
    other = Item.objects.filter(category='21')
    context = {'other': other}
    return render(request, 'sorting/other.html', context)


@login_required()
def other_electronics(request):
    other_electronics = Item.objects.filter(category='22')
    context = {'other_electronics': other_electronics}
    return render(request, 'sorting/other_electronics.html', context)


@login_required()
def other_beauty_cosmetics(request):
    other_beauty_cosmetics = Item.objects.filter(category='23')
    context = {'other_beauty_cosmetics': other_beauty_cosmetics}
    return render(request, 'sorting/other_beauty_cosmetics.html', context)

@login_required()
def other_vehicles(request):
    other_vehicles = Item.objects.filter(category='24')
    context = {'other_vehicles': other_vehicles}
    return render(request, 'sorting/other_vehicles.html', context)


@login_required()
def other_homeware(request):
    other_homeware = Item.objects.filter(category='25')
    context = {'other_homeware': other_homeware}
    return render(request, 'sorting/other_homeware.html', context)

sorting/templates/sorting/clothing_estore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Estore</title>
</head>
{% extends 'store_information/base.html' %}
{% load static %}
<body>




{% block conntent %}

    <header class="H1">
        <image class="logo" src="{% static '/media/main-logo.png' %}"></image>

         <div class="search-nav-bar">
            <form action="{% url 'search_results' %}" method="get">
                <input name="q" type="text" placeholder="Search...">
            </form>

        </div>

        {% if request.user.is_authenticated %}

            <div class="nav-tab">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>
                <div class="user"onclick="window.location.href='{% url 'account:profile' %}';">
                    <img src="{{ request.user.profile_pic.url }}" alt="">
                </div>
             </div>

            <div class="sml-nav">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>

                <div class="sml-nav-2">

                    <button class="mobile-toggle"
                        aria-controls="pry-nav" aria-expanded="false">
                        <span class="sr-only">Menu</span>
                    </button>
                </div>
            </div>
        {% else %}
            <a href="{% url 'account:login' %}" class="btn">Sign In</a>
        {% endif %}



    </header>

    <header class="H2-container">
        <nav class="nav-bar-bar">
            <ul>
                <li><a href="{% url 'store_information:index' %}">Home</a></li>
                <li><a href="{% url 'store_information:about_us' %}">About Us</a></li>
                <li><a href="{% url 'store_information:gallery' %}">Gallery</a></li>
                <li><a href="{% url 'store_information:estores' %}">E Store</a></li>
                <li><a href="{% url 'store_information:hotdeals' %}">Hot Deals</a></li>
            </ul>
        </nav>
    </header>

    <section class="container">
        <h1>#E-Stores</h1>
        <p>Visit our online stores by our different vendors</p>
        <a href="{% url 'store_information:create_estore' %}" class="btn-S">Create E-Store</a>
    </section>

    <section class="cat-menu">
        <nav>
            <label for="btwn" class="btn-D">Categories
            <span class="fas fa-caret-down"></span>
        </label>
        <input class="tick" type = "checkbox" id="btwn">
         <ul class="menu-bar">
             <li>
            <label for="btwn-1" class="first-menu">Clothing
                <span class="fas fa-caret-down"></span>
            </label>
            <input class="tick" type = "checkbox" id="btwn-1">
                        <ul>
                <li><a href="{% url 'sort:clothing_estore'%}">Men Collection</a></li>
                <li><a href="{% url 'sort:clothing_estore'%}">Ladies Collection</a></li>
                <li><a href="{% url 'sort:clothing_estore'%}">Kids Collection</a></li>
            </ul>
            </li>
            <li>
                <label for="btwn-2" class="second-menu">Electronics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-2">

                <ul>
                    <li><a href="{% url 'sort:electronics_estore'%}">Phones and Tablets</a></li>
                    <li><a href="{% url 'sort:electronics_estore'%}">Watches</a></li>
                    <li><a href="{% url 'sort:electronics_estore'%}">Laptops</a></li>
                    <li><a href="{% url 'sort:electronics_estore'%}">Accessories</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-3" class="third-menu">Homeware
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-3">
                 <ul>
                    <li><a href="{% url 'sort:homeware_estore'%}">Lounge and Dining</a></li>
                    <li><a href="{% url 'sort:homeware_estore'%}">Kitchen</a></li>
                    <li><a href="{% url 'sort:homeware_estore'%}">Bedroom</a></li>
                    <li><a href="{% url 'sort:homeware_estore'%}">Bathroom</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-4" class="fourth-menu">Cosmetics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-4">
                 <ul>
                    <li><a href="{% url 'sort:cosmetics_estore' %}">Skin Care</a></li>
                    <li><a href="{% url 'sort:cosmetics_estore' %}">Frangrances</a></li>
                    <li><a href="{% url 'sort:cosmetics_estore' %}">Other</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-5" class="fifth-menu">Vehicles
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-5">
                 <ul>
                    <li><a href="{% url 'sort:vehicles_estore' %}">Cars</a></li>
                    <li><a href="{% url 'sort:vehicles_estore' %}">Buses</a></li>
                    <li><a href="{% url 'sort:vehicles_estore' %}">Trucks</a></li>
                    <li><a href="{% url 'sort:vehicles_estore' %}">Other</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-6" class="sixth-menu">
                    <a href="{% url 'sort:other_estore' %}" class="sixth-menu">Other</a>
                </label>
            </li>
         </ul>
        </nav>

    </section>



    <section id="stores" class="featured">

        <div class="store-card">
            {% for estore in clothing_estore %}
                 <div class="store-card-top">

                    <div class="store-details">
                            <h2 class="store">{{ estore.store_name }}</h2>
                        <div class="location">
                            <i class="fas fa-map-marker-alt"></i>
                            <h3>{{ estore.location }}</h3>
                        </div>
                    </div>

                    <div class="store-pro">
                        <img src="{{ estore.profile_pic.url }}" alt="">
                    </div>

                </div>
                <div class="store-card-bottom">
                    <a href="{% url 'store_information:estores_estore' estore.id %}" class="btn-St">Visit Store</a>
                </div>
        {% endfor %}
        </div>


    </section>

    <section id="pagination" class="featured">
        <a href="#">1</a>
        <a href="#">2</a>
        <a href="#">3</a>
        <a href="#"><i class="fas fa-chevron-right"></i></a>
    </section>

    <footer class="featured">
        <div class="col">
            <img class="logor" src="{% static 'media/main-logo.png' %}" alt="">
            <h3>Contact</h3>
            <p><strong>WhatsApp :</strong> +263 77 684 2894</p>
            <p><strong>Phone : </strong>  +263 77 635 0319 </p>
            <div class="follow">
                <h3>Follow Us</h3>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="{% url 'store_information:about_us' %}">About Us</a>
            <a href="#">Terms & Conditions</a>
            <a href="#">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            <a href="#">Sign In</a>
            <a href="#">My Wishlist</a>
            <a href="{% url 'store_information:about_us' %}">Help</a>
        </div>

        <div class="col install">
            <h3>Install Our App</h3>
            <p>For easier access of our content</p>
            <div class="row">
                <!-- This is the buttons for downoloading our app-->
            </div>
            <p>Secured Payment Gateways</p>
            <div class="row">
                <!-- Payment gateways i.e Ecocash -->
            </div>
        </div>


        <section class="line">
            <p>Copyright 2022 @SquareMarket. All rights reserved.</p>
        </section>

    </footer>
{% endblock conntent %}

</body>
</html>

sorting/templates/sorting/cosmetics_estore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Estore</title>
</head>
{% extends 'store_information/base.html' %}
{% load static %}
<body>




{% block conntent %}

    <header class="H1">
        <image class="logo" src="{% static '/media/main-logo.png' %}"></image>

        <div class="search-nav-bar">
            <form action="{% url 'search_results' %}" method="get">
                <input name="q" type="text" placeholder="Search...">
            </form>

        </div>

        {% if request.user.is_authenticated %}

            <div class="nav-tab">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>
                <div class="user"onclick="window.location.href='{% url 'account:profile' %}';">
                    <img src="{{ request.user.profile_pic.url }}" alt="">
                </div>
             </div>

            <div class="sml-nav">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>

                <div class="sml-nav-2">

                    <button class="mobile-toggle"
                        aria-controls="pry-nav" aria-expanded="false">
                        <span class="sr-only">Menu</span>
                    </button>
                </div>
            </div>
        {% else %}
            <a href="{% url 'account:login' %}" class="btn">Sign In</a>
        {% endif %}



    </header>

    <header class="H2-container">
        <nav class="nav-bar-bar">
            <ul>
                <li><a href="{% url 'store_information:index' %}">Home</a></li>
                <li><a href="{% url 'store_information:about_us' %}">About Us</a></li>
                <li><a href="{% url 'store_information:gallery' %}">Gallery</a></li>
                <li><a href="{% url 'store_information:estores' %}">E Store</a></li>
                <li><a href="{% url 'store_information:hotdeals' %}">Hot Deals</a></li>
            </ul>
        </nav>
    </header>

    <section class="container">
        <h1>#E-Stores</h1>
        <p>Visit our online stores by our different vendors</p>
        <a href="{% url 'store_information:create_estore' %}" class="btn-S">Create E-Store</a>
    </section>

    <section class="cat-menu">
        <nav>
            <label for="btwn" class="btn-D">Categories
            <span class="fas fa-caret-down"></span>
        </label>
        <input class="tick" type = "checkbox" id="btwn">
         <ul class="menu-bar">
             <li>
            <label for="btwn-1" class="first-menu">Clothing
                <span class="fas fa-caret-down"></span>
            </label>
            <input class="tick" type = "checkbox" id="btwn-1">
                        <ul>
                <li><a href="{% url 'sort:clothing_estore'%}">Men Collection</a></li>
                <li><a href="{% url 'sort:clothing_estore'%}">Ladies Collection</a></li>
                <li><a href="{% url 'sort:clothing_estore'%}">Kids Collection</a></li>
            </ul>
            </li>
            <li>
                <label for="btwn-2" class="second-menu">Electronics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-2">

                <ul>
                    <li><a href="{% url 'sort:electronics_estore'%}">Phones and Tablets</a></li>
                    <li><a href="{% url 'sort:electronics_estore'%}">Watches</a></li>
                    <li><a href="{% url 'sort:electronics_estore'%}">Laptops</a></li>
                    <li><a href="{% url 'sort:electronics_estore'%}">Accessories</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-3" class="third-menu">Homeware
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-3">
                 <ul>
                    <li><a href="{% url 'sort:homeware_estore'%}">Lounge and Dining</a></li>
                    <li><a href="{% url 'sort:homeware_estore'%}">Kitchen</a></li>
                    <li><a href="{% url 'sort:homeware_estore'%}">Bedroom</a></li>
                    <li><a href="{% url 'sort:homeware_estore'%}">Bathroom</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-4" class="fourth-menu">Cosmetics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-4">
                 <ul>
                    <li><a href="{% url 'sort:cosmetics_estore' %}">Skin Care</a></li>
                    <li><a href="{% url 'sort:cosmetics_estore' %}">Frangrances</a></li>
                    <li><a href="{% url 'sort:cosmetics_estore' %}">Other</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-5" class="fifth-menu">Vehicles
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-5">
                 <ul>
                    <li><a href="{% url 'sort:vehicles_estore' %}">Cars</a></li>
                    <li><a href="{% url 'sort:vehicles_estore' %}">Buses</a></li>
                    <li><a href="{% url 'sort:vehicles_estore' %}">Trucks</a></li>
                    <li><a href="{% url 'sort:vehicles_estore' %}">Other</a></li>
                </ul>
            </li>
            <li>
                <label for="btwn-6" class="sixth-menu">
                    <a href="{% url 'sort:other_estore' %}" class="sixth-menu">Other</a>
                </label>
            </li>
         </ul>
        </nav>

    </section>



    <section id="stores" class="featured">

        <div class="store-card">
            {% for estore in cosmetics_estore %}
                 <div class="store-card-top">

                    <div class="store-details">
                            <h2 class="store">{{ estore.store_name }}</h2>
                        <div class="location">
                            <i class="fas fa-map-marker-alt"></i>
                            <h3>{{ estore.location }}</h3>
                        </div>
                    </div>

                    <div class="store-pro">
                        <img src="{{ estore.profile_pic.url }}" alt="">
                    </div>

                </div>
                <div class="store-card-bottom">
                    <a href="{% url 'store_information:estores_estore' estore.id %}" class="btn-St">Visit Store</a>
                </div>
        {% endfor %}
        </div>


    </section>

    <section id="pagination" class="featured">
        <a href="#">1</a>
        <a href="#">2</a>
        <a href="#">3</a>
        <a href="#"><i class="fas fa-chevron-right"></i></a>
    </section>

    <footer class="featured">
        <div class="col">
            <img class="logor" src="{% static 'media/main-logo.png' %}" alt="">
            <h3>Contact</h3>
            <p><strong>WhatsApp :</strong> +263 77 684 2894</p>
            <p><strong>Phone : </strong>  +263 77 635 0319 </p>
            <div class="follow">
                <h3>Follow Us</h3>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="{% url 'store_information:about_us' %}">About Us</a>
            <a href="#">Terms & Conditions</a>
            <a href="#">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            <a href="#">Sign In</a>
            <a href="#">My Wishlist</a>
            <a href="{% url 'store_information:about_us' %}">Help</a>
        </div>

        <div class="col install">
            <h3>Install Our App</h3>
            <p>For easier access of our content</p>
            <div class="row">
                <!-- This is the buttons for downoloading our app-->
            </div>
            <p>Secured Payment Gateways</p>
            <div class="row">
                <!-- Payment gateways i.e Ecocash -->
            </div>
        </div>


        <section class="line">
            <p>Copyright 2022 @SquareMarket. All rights reserved.</p>
        </section>

    </footer>
{% endblock conntent %}

</body>
</html>