account/urls.py
from django.contrib.auth.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('register/', views.registration_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.my_profile, name='profile'),
    path('account/', views.account_view, name='account')
]

edit/urls.py
from django.urls import path, include
from . import views

app_name = 'edit'
urlpatterns = [
    path('profile/', views.profile, name='profile')
]

estore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store_information.urls')),
    path('accounts/', include('account.urls')),
    path('search/', include('search.urls')),
    path('sort/', include('sorting.urls')),
    path('edit/', include('edit.urls')),
    path('sort_estore/', include('sorting_estore.urls')),
    path('estore_estore_sort/', include('estore_estore_sort.urls')),
    path('payments/', include('payment.urls'))
]

estore_estore_sort/urls.py
from django.urls import path, include
from . import views

app_name = 'estore_estore_sort'
urlpatterns = [
    path('men_collection/', views.men_collection, name='men_collection'),
    path('ladies_collection/', views.ladies_collection, name='ladies_collection'),
    path('kids_collection/', views.kids_collection, name='kids_collection'),
    path('phones_tablets/', views.phones_tablets, name='phones_tablets'),
    path('laptops/', views.laptops, name='laptops'),
    path('appliances_machinery/', views.appliances_machinery, name='appliances_machinery'),
    path('accessories/', views.accessories, name='accessories'),
    path('dining_lounge/', views.dining_lounge, name='dining_lounge'),
    path('kitchen/', views.kitchen, name='kitchen'),
    path('bedroom/', views.bedroom, name='bedroom'),
    path('bathroom/', views.bathroom, name='bathroom'),
    path('skin_care/', views.skin_care, name='skin_care'),
    path('hair_products/', views.hair_products, name='hair_products'),
    path('fragrances/', views.fragrances, name='fragrances'),
    path('cars/', views.cars, name='cars'),
    path('trucks/', views.trucks, name='trucks'),
    path('vehicle_parts/', views.vehicle_parts, name='vehicle_parts'),
    path('event_services/', views.event_services, name='event_services'),
    path('food_services/', views.food_services, name='food_services'),
    path('other_services/', views.other_services, name='other_services'),
    path('other/', views.other, name='other'),

]

store_information/urls.py
from django.contrib.auth.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'store_information'

urlpatterns = [
    path('', views.index, name='index'),
    path('gallery/', views.items, name='gallery'),
    path('sell_product/', views.upload_item, name='sell_product'),
    path('create_estore/', views.create_estore, name='create_estore'),
    path('item_estore/', views.item_estore, name='item_estore'),
    path('welcome/', views.welcome, name='welcome'),
    path('about_estore/', views.about_estore, name='about_estore'),
    path('about_us/', views.about_us, name='about_us'),
    path('gallery/<int:gallerie_id>/', views.gallerie, name='gallerie'),
    path('estores/', views.estores, name='estores'),
    path('hotdeals/', views.hotdeals, name='hotdeals'),
    path('upload_hot_deals/', views.upload_hot_deals, name='upload_hot_deals'),
    path('hotdeals/<int:hotdeal_id>/', views.hotdeal, name='hotdeal'),
    path('estores_estore/<int:estore_id>/', views.estores_estore, name='estores_estore'),
    path('product_estore/<int:product_estore_id>/', views.product_estore, name='product_estore'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('my_listings/', views.my_listings, name='my_listings'),
    path('my_gallery/', views.my_gallery, name='my_gallery'),
    path('estore_coupon/', views.estore_coupon, name='estore_coupon'),
    path('create/', views.create, name='create'),
    path('no_store', views.no_store, name='no_store'),
    path('edit_store/<int:estore_id>/', views.edit_store, name='edit_store'),
    path('terms_conditions/', views.terms_conditions, name='terms_conditions')

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

estore_estore_sort/models.py
from django.db import models

# Create your models here.

estore_estore_sort/views.py
from django.shortcuts import render
from store_information.models import ItemEstore, Item, EStore, HotDeals
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required()
def men_collection(request):
    men_collection = ItemEstore.objects.filter(category='1')
    context = {'men_collection': men_collection}
    return render(request, 'estore_estore_sort/men_collection.html', context)


@login_required()
def ladies_collection(request):
    ladies_collection = ItemEstore.objects.filter(category='2')
    context = {'ladies_collection': ladies_collection}
    return render(request, 'estore_estore_sort/ladies_collection.html', context)


@login_required()
def kids_collection(request):
    kids_collection = ItemEstore.objects.filter(category='3')
    context = {'kids_collection': kids_collection}
    return render(request, 'estore_estore_sort/kids_collection.html', context)


@login_required()
def phones_tablets(request):
    phones_tablets = ItemEstore.objects.filter(category='4')
    context = {'phones_tablets': phones_tablets}
    return render(request, 'estore_estore_sort/phones_tablets.html', context)


@login_required()
def laptops(request):
    laptops = ItemEstore.objects.filter(category='5')
    context = {'laptops': laptops}
    return render(request, 'estore_estore_sort/laptops.html', context)


@login_required()
def appliances_machinery(request):
    appliances_machinery = ItemEstore.objects.filter(category='6')
    context = {'appliances_machinery': appliances_machinery}
    return render(request, 'estore_estore_sort/appliances_machinery.html', context)


@login_required()
def accessories(request):
    accessories = ItemEstore.objects.filter(category='7')
    context = {'accessories': accessories}
    return render(request, 'estore_estore_sort/accessories.html', context)


@login_required()
def dining_lounge(request):
    dining_lounge = ItemEstore.objects.filter(category='8')
    context = {'dining_lounge': dining_lounge}
    return render(request, 'estore_estore_sort/dining_lounge.html', context)


@login_required()
def kitchen(request):
    kitchen = ItemEstore.objects.filter(category='9')
    context = {'kitchen': kitchen}
    return render(request, 'estore_estore_sort/kitchen.html', context)


@login_required()
def bedroom(request):
    bedroom = ItemEstore.objects.filter(category='10')
    context = {'bedroom': bedroom}
    return render(request, 'estore_estore_sort/bedroom.html', context)


@login_required()
def bathroom(request):
    bathroom = ItemEstore.objects.filter(category='11')
    context = {'bathroom': bathroom}
    return render(request, 'estore_estore_sort/bathroom.html', context)


@login_required()
def skin_care(request):
    skin_care = ItemEstore.objects.filter(category='12')
    context = {'skin_care': skin_care}
    return render(request, 'estore_estore_sort/skin_care.html', context)


@login_required()
def hair_products(request):
    hair_products = ItemEstore.objects.filter(category='13')
    context = {'hair_products': hair_products}
    return render(request, 'estore_estore_sort/hair_products.html', context)


@login_required()
def fragrances(request):
    fragrances = ItemEstore.objects.filter(category='14')
    context = {'fragrances': fragrances}
    return render(request, 'estore_estore_sort/fragrances.html', context)


@login_required()
def cars(request):
    cars = ItemEstore.objects.filter(category='15')
    context = {'cars': cars}
    return render(request, 'estore_estore_sort/cars.html', context)


@login_required()
def trucks(request):
    trucks = ItemEstore.objects.filter(category='16')
    context = {'trucks': trucks}
    return render(request, 'estore_estore_sort/trucks.html', context)


@login_required()
def vehicle_parts(request):
    vehicle_parts = ItemEstore.objects.filter(category='17')
    context = {'vehicle_parts': vehicle_parts}
    return render(request, 'estore_estore_sort/vehicle_parts.html', context)


@login_required()
def event_services(request):
    event_services = ItemEstore.objects.filter(category='18')
    context = {'event_services': event_services}
    return render(request, 'estore_estore_sort/event_services.html', context)


@login_required()
def food_services(request):
    food_services = ItemEstore.objects.filter(category='19')
    context = {'food_services': food_services}
    return render(request, 'estore_estore_sort/food_services.html', context)


@login_required()
def other_services(request):
    other_services = ItemEstore.objects.filter(category='20')
    context = {'other_services': other_services}
    return render(request, 'estore_estore_sort/other_services.html', context)


@login_required()
def other(request):
    other = ItemEstore.objects.filter(category='21')
    context = {'other': other}
    return render(request, 'estore_estore_sort/other.html', context)

# Create your views here.

estore_estore_sort/templates/estore_estore_sort/accessories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Accessories</title>
</head>
{% extends 'store_information/base.html' %}
{% load static %}
<body>
{% block conntent %}


    <header class="H1">
        <image class="logo" src="{% static '/media/main-logo.png' %}"></image>
        <form action="{% url 'product_store_search_results' %}" method="get">
            <div class="search-nav-bar">

                    <input name="q" type="text" placeholder="Search...">

            </div>
         </form>





         {% if request.user.is_authenticated %}

            <div class="nav-tab">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>
                <div class="user"onclick="window.location.href='{% url 'account:profile' %}';">
                    <img src="{{ request.user.profile_pic.url }}" alt="">
                </div>
             </div>

            <div class="sml-nav">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>

                <div class="sml-nav-2">

                    <button class="mobile-toggle"
                        aria-controls="pry-nav" aria-expanded="false">
                        <span class="sr-only">Menu</span>
                    </button>
                </div>
            </div>
        {% else %}
            <a href="{% url 'account:login' %}" class="btn">Sign In</a>
        {% endif %}

    </header>



    <section class="container-details">
        <div class="vendor">
            <img src="{{ estores_estore.owner.profile_pic.url }}" alt="">
            <h2>{{ estores_estore.owner.username }}</h2>
            <div class="location S1">
                <i class="fas fa-map-marker-alt"></i>
                <h3>{{ estores_estore.owner.location }}</h3>
            </div>
            <div class="location contact-S">
                <i class="fab fa-whatsapp"></i>
                <h3><a href="https://wa.me/263{{ estores_estore.owner.phone_number }}" target='_blank'>{{ estores_estore.owner.phone_number }}</a></h3>
            </div>

        </div>

        <div class="store-back">
            <h1>{{ estores_estore.store_name }}</h1>
            <p>{{ estores_estore.category }}</p>


        </div>
    </section>


    <section class="line Store-line">
        <hr style="width:20%; border-radius: 8px; height:5px; background-color:#008dff; margin-left: auto; margin-right: auto; color: #008dff;">
    </section>

    <section class="cat-menu">
        <nav>
            <label for="btwn" class="btn-D">Select Category
            <span class="fas fa-caret-down"></span>
        </label>
        <input class="tick" type = "checkbox" id="btwn">
         <ul class="menu-bar">

            <li>
                <label for="btwn-2" class="second-menu">Electronics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-2">

                <ul>
                    <li><a href="#">Phones and Tablets</a></li>
                    <li><a href="#">Watches</a></li>
                    <li><a href="#">Laptops</a></li>
                    <li><a href="#">Accessories</a></li>
                </ul>
            </li>

         </ul>
        </nav>

    </section>

    <section id="product1" class="featured">

        <div class="pro-container">
            {% for item in accessories %}

            <div class="pro">
                <img src="{{ item.image1.url }}" alt="">
                <div class="label storelabel">
                    <div class="pro-info">
                        <a href="{% url 'store_information:product_estore' item.id %}"><h3>{{ item.product_name }}</h3></a>
                        <h2>{{ item.price }}</h2>
                    </div>
                    <div class="store-wish">
                        <span  class="add-wishlist"><i class="fas fa-cart-plus"></i></span>
                    </div>

                </div>

            </div>
            {% empty %}
                <li>No items have been added as of yet</li>
            {% endfor %}
        </div>





    </section>

    <footer class="featured foot-det">
        <div class="col">
            <img class="logor" src="{% static '/media/main-logo.png' %}" alt="">
            <h3>Contact</h3>
            <p><strong>WhatsApp :</strong> +263 77 684 2894</p>
            <p><strong>Phone : </strong>  +263 77 635 0319 </p>
            <div class="follow">
                <h3>Follow Us</h3>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="{% url 'store_information:about_us' %}">About Us</a>
            <a href="{% url 'store_information:terms_conditions' %}">Terms & Conditions</a>
            <a href="#">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            <a href="{% url 'account:login' %}">Sign In</a>
            <a href="#">My Wishlist</a>
            <a href="{% url 'store_information:about_us' %}">Help</a>
        </div>

        <div class="col install">
            <h3>Install Our App</h3>
            <p>Coming soon</p>
            <div class="row app">
                <!-- This is the buttons for downoloading our app-->
                <img src="{% static 'media/undraw_under_construction_-46-pa.svg' %}" alt="">
            </div>
            <p>Secured Payment Gateways</p>
            <div class="row pay">
                <!-- Payment gateways i.e Ecocash -->
               <ul>
                   <li>Ecocash</li>
                   <li>VISA Mastercard</li>
                   <li>Direct Bank Transfer</li>
               </ul>
            </div>
        </div>


        <section class="line">
            <p>Copyright 2022 @SquareMarket. All rights reserved.</p>
        </section>

    </footer>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock conntent %}

</body>
</html>

estore_estore_sort/templates/estore_estore_sort/appliances_machinery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Appliances and Machinery</title>
</head>
{% extends 'store_information/base.html' %}
{% load static %}
<body>
{% block conntent %}


    <header class="H1">
        <image class="logo" src="{% static '/media/main-logo.png' %}"></image>
        <form action="{% url 'product_store_search_results' %}" method="get">
            <div class="search-nav-bar">

                    <input name="q" type="text" placeholder="Search...">

            </div>
         </form>





         {% if request.user.is_authenticated %}

            <div class="nav-tab">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>
                <div class="user"onclick="window.location.href='{% url 'account:profile' %}';">
                    <img src="{{ request.user.profile_pic.url }}" alt="">
                </div>
             </div>

            <div class="sml-nav">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>

                <div class="sml-nav-2">

                    <button class="mobile-toggle"
                        aria-controls="pry-nav" aria-expanded="false">
                        <span class="sr-only">Menu</span>
                    </button>
                </div>
            </div>
        {% else %}
            <a href="{% url 'account:login' %}" class="btn">Sign In</a>
        {% endif %}

    </header>



    <section class="container-details">
        <div class="vendor">
            <img src="{{ estores_estore.owner.profile_pic.url }}" alt="">
            <h2>{{ estores_estore.owner.username }}</h2>
            <div class="location S1">
                <i class="fas fa-map-marker-alt"></i>
                <h3>{{ estores_estore.owner.location }}</h3>
            </div>
            <div class="location contact-S">
                <i class="fab fa-whatsapp"></i>
                <h3><a href="https://wa.me/263{{ estores_estore.owner.phone_number }}" target='_blank'>{{ estores_estore.owner.phone_number }}</a></h3>
            </div>

        </div>

        <div class="store-back">
            <h1>{{ estores_estore.store_name }}</h1>
            <p>{{ estores_estore.category }}</p>


        </div>
    </section>


    <section class="line Store-line">
        <hr style="width:20%; border-radius: 8px; height:5px; background-color:#008dff; margin-left: auto; margin-right: auto; color: #008dff;">
    </section>

    <section class="cat-menu">
        <nav>
            <label for="btwn" class="btn-D">Select Category
            <span class="fas fa-caret-down"></span>
        </label>
        <input class="tick" type = "checkbox" id="btwn">
         <ul class="menu-bar">

            <li>
                <label for="btwn-2" class="second-menu">Electronics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-2">

                <ul>
                    <li><a href="#">Phones and Tablets</a></li>
                    <li><a href="#">Watches</a></li>
                    <li><a href="#">Laptops</a></li>
                    <li><a href="#">Accessories</a></li>
                </ul>
            </li>

         </ul>
        </nav>

    </section>

    <section id="product1" class="featured">

        <div class="pro-container">
            {% for item in appliances_machinery %}

            <div class="pro">
                <img src="{{ item.image1.url }}" alt="">
                <div class="label storelabel">
                    <div class="pro-info">
                        <a href="{% url 'store_information:product_estore' item.id %}"><h3>{{ item.product_name }}</h3></a>
                        <h2>{{ item.price }}</h2>
                    </div>
                    <div class="store-wish">
                        <span  class="add-wishlist"><i class="fas fa-cart-plus"></i></span>
                    </div>

                </div>

            </div>
            {% empty %}
                <li>No items have been added as of yet</li>
            {% endfor %}
        </div>





    </section>

    <footer class="featured foot-det">
        <div class="col">
            <img class="logor" src="{% static '/media/main-logo.png' %}" alt="">
            <h3>Contact</h3>
            <p><strong>WhatsApp :</strong> +263 77 684 2894</p>
            <p><strong>Phone : </strong>  +263 77 635 0319 </p>
            <div class="follow">
                <h3>Follow Us</h3>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="{% url 'store_information:about_us' %}">About Us</a>
            <a href="{% url 'store_information:terms_conditions' %}">Terms & Conditions</a>
            <a href="#">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            <a href="{% url 'account:login' %}">Sign In</a>
            <a href="#">My Wishlist</a>
            <a href="{% url 'store_information:about_us' %}">Help</a>
        </div>

        <div class="col install">
            <h3>Install Our App</h3>
            <p>Coming soon</p>
            <div class="row app">
                <!-- This is the buttons for downoloading our app-->
                <img src="{% static 'media/undraw_under_construction_-46-pa.svg' %}" alt="">
            </div>
            <p>Secured Payment Gateways</p>
            <div class="row pay">
                <!-- Payment gateways i.e Ecocash -->
               <ul>
                   <li>Ecocash</li>
                   <li>VISA Mastercard</li>
                   <li>Direct Bank Transfer</li>
               </ul>
            </div>
        </div>


        <section class="line">
            <p>Copyright 2022 @SquareMarket. All rights reserved.</p>
        </section>

    </footer>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock conntent %}

</body>
</html>

estore_estore_sort/templates/estore_estore_sort/bedroom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bedroom</title>
</head>
{% extends 'store_information/base.html' %}
{% load static %}
<body>
{% block conntent %}


    <header class="H1">
        <image class="logo" src="{% static '/media/main-logo.png' %}"></image>
        <form action="{% url 'product_store_search_results' %}" method="get">
            <div class="search-nav-bar">

                    <input name="q" type="text" placeholder="Search...">

            </div>
         </form>





         {% if request.user.is_authenticated %}

            <div class="nav-tab">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>
                <div class="user"onclick="window.location.href='{% url 'account:profile' %}';">
                    <img src="{{ request.user.profile_pic.url }}" alt="">
                </div>
             </div>

            <div class="sml-nav">
                <div class="sml-search">
                    <a href="#"><i class="fas fa-search"></i></a>
                </div>

                <div class="sml-nav-2">

                    <button class="mobile-toggle"
                        aria-controls="pry-nav" aria-expanded="false">
                        <span class="sr-only">Menu</span>
                    </button>
                </div>
            </div>
        {% else %}
            <a href="{% url 'account:login' %}" class="btn">Sign In</a>
        {% endif %}

    </header>



    <section class="container-details">
        <div class="vendor">
            <img src="{{ estores_estore.owner.profile_pic.url }}" alt="">
            <h2>{{ estores_estore.owner.username }}</h2>
            <div class="location S1">
                <i class="fas fa-map-marker-alt"></i>
                <h3>{{ estores_estore.owner.location }}</h3>
            </div>
            <div class="location contact-S">
                <i class="fab fa-whatsapp"></i>
                <h3><a href="https://wa.me/263{{ estores_estore.owner.phone_number }}" target='_blank'>{{ estores_estore.owner.phone_number }}</a></h3>
            </div>

        </div>

        <div class="store-back">
            <h1>{{ estores_estore.store_name }}</h1>
            <p>{{ estores_estore.category }}</p>


        </div>
    </section>


    <section class="line Store-line">
        <hr style="width:20%; border-radius: 8px; height:5px; background-color:#008dff; margin-left: auto; margin-right: auto; color: #008dff;">
    </section>

    <section class="cat-menu">
        <nav>
            <label for="btwn" class="btn-D">Select Category
            <span class="fas fa-caret-down"></span>
        </label>
        <input class="tick" type = "checkbox" id="btwn">
         <ul class="menu-bar">

            <li>
                <label for="btwn-2" class="second-menu">Electronics
                    <span class="fas fa-caret-down"></span>
                </label>
                <input class="tick" type = "checkbox" id="btwn-2">

                <ul>
                    <li><a href="#">Phones and Tablets</a></li>
                    <li><a href="#">Watches</a></li>
                    <li><a href="#">Laptops</a></li>
                    <li><a href="#">Accessories</a></li>
                </ul>
            </li>

         </ul>
        </nav>

    </section>

    <section id="product1" class="featured">

        <div class="pro-container">
            {% for item in bedroom %}

            <div class="pro">
                <img src="{{ item.image1.url }}" alt="">
                <div class="label storelabel">
                    <div class="pro-info">
                        <a href="{% url 'store_information:product_estore' item.id %}"><h3>{{ item.product_name }}</h3></a>
                        <h2>{{ item.price }}</h2>
                    </div>
                    <div class="store-wish">
                        <span  class="add-wishlist"><i class="fas fa-cart-plus"></i></span>
                    </div>

                </div>

            </div>
            {% empty %}
                <li>No items have been added as of yet</li>
            {% endfor %}
        </div>





    </section>

    <footer class="featured foot-det">
        <div class="col">
            <img class="logor" src="{% static '/media/main-logo.png' %}" alt="">
            <h3>Contact</h3>
            <p><strong>WhatsApp :</strong> +263 77 684 2894</p>
            <p><strong>Phone : </strong>  +263 77 635 0319 </p>
            <div class="follow">
                <h3>Follow Us</h3>
                <div class="icon">
                    <i class="fab fa-facebook-f"></i>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h3>About</h3>
            <a href="{% url 'store_information:about_us' %}">About Us</a>
            <a href="{% url 'store_information:terms_conditions' %}">Terms & Conditions</a>
            <a href="#">Privacy Policy</a>
        </div>

        <div class="col">
            <h3>My Account</h3>
            <a href="{% url 'account:login' %}">Sign In</a>
            <a href="#">My Wishlist</a>
            <a href="{% url 'store_information:about_us' %}">Help</a>
        </div>

        <div class="col install">
            <h3>Install Our App</h3>
            <p>Coming soon</p>
            <div class="row app">
                <!-- This is the buttons for downoloading our app-->
                <img src="{% static 'media/undraw_under_construction_-46-pa.svg' %}" alt="">
            </div>
            <p>Secured Payment Gateways</p>
            <div class="row pay">
                <!-- Payment gateways i.e Ecocash -->
               <ul>
                   <li>Ecocash</li>
                   <li>VISA Mastercard</li>
                   <li>Direct Bank Transfer</li>
               </ul>
            </div>
        </div>


        <section class="line">
            <p>Copyright 2022 @SquareMarket. All rights reserved.</p>
        </section>

    </footer>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock conntent %}

</body>
</html>